const schemes = [
  {
    schemeID: "SCHEME-001",
    title: "ADA Research Grant",
    description: "Financial assistance for researchers.",
    status: "Open",
    eligibility: "Researchers with a valid research proposal.",
    benefits: "Up to $50,000 in funding.",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    schemeID: "SCHEME-002",
    title: "ADA Entrepreneurship Support",
    description: "Funding and mentorship for startups.",
    status: "Application in Progress",
    eligibility: "Startups less than 3 years old.",
    benefits: "Mentorship and up to $100,000 in funding.",
    startDate: "2024-03-01",
    endDate: "2024-09-30",
  },
  {
    schemeID: "SCHEME-003",
    title: "ADA Education Scholarship",
    description: "Scholarships for students.",
    status: "Closed",
    eligibility: "Students with a minimum GPA of 3.5.",
    benefits: "Full tuition coverage.",
    startDate: "2023-09-01",
    endDate: "2024-05-31",
  },
  {
    schemeID: "SCHEME-004",
    title: "ADA Women Empowerment Program",
    description: "Skill development and funding for women.",
    status: "Open",
    eligibility: "Women entrepreneurs and professionals.",
    benefits: "Skill development workshops and funding.",
    startDate: "2024-02-15",
    endDate: "2024-11-30",
  },
  {
    schemeID: "SCHEME-005",
    title: "ADA Health Initiative",
    description: "Support for health-related projects.",
    status: "Open",
    eligibility: "Health professionals and organizations.",
    benefits: "Funding and resources for health projects.",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
  {
    schemeID: "SCHEME-006",
    title: "ADA Environmental Grant",
    description: "Funding for environmental conservation projects.",
    status: "Application in Progress",
    eligibility: "Environmental NGOs and activists.",
    benefits: "Up to $75,000 in funding.",
    startDate: "2024-04-01",
    endDate: "2024-10-31",
  },
  {
    schemeID: "SCHEME-007",
    title: "ADA Technology Innovation Fund",
    description: "Grants for tech innovation.",
    status: "Closed",
    eligibility: "Tech startups and innovators.",
    benefits: "Funding and access to tech resources.",
    startDate: "2023-06-01",
    endDate: "2023-12-31",
  },
  {
    schemeID: "SCHEME-008",
    title: "ADA Community Development Program",
    description: "Support for community development initiatives.",
    status: "Open",
    eligibility: "Community leaders and organizations.",
    benefits: "Funding and support for community projects.",
    startDate: "2024-03-15",
    endDate: "2024-12-15",
  },
  {
    schemeID: "SCHEME-009",
    title: "ADA Arts and Culture Grant",
    description: "Funding for arts and culture projects.",
    status: "Application in Progress",
    eligibility: "Artists and cultural organizations.",
    benefits: "Up to $30,000 in funding.",
    startDate: "2024-05-01",
    endDate: "2024-11-30",
  },
  {
    schemeID: "SCHEME-010",
    title: "ADA Sports Scholarship",
    description: "Scholarships for athletes.",
    status: "Closed",
    eligibility: "Athletes with a proven track record.",
    benefits: "Full scholarship and training support.",
    startDate: "2023-08-01",
    endDate: "2024-06-30",
  },
  {
    schemeID: "SCHEME-011",
    title: "ADA Rural Development Scheme",
    description: "Support for rural development projects.",
    status: "Open",
    eligibility: "Rural communities and organizations.",
    benefits: "Funding and resources for rural development.",
    startDate: "2024-02-01",
    endDate: "2024-12-31",
  },
  {
    schemeID: "SCHEME-012",
    title: "ADA Youth Empowerment Program",
    description: "Funding and mentorship for youth.",
    status: "Application in Progress",
    eligibility: "Youth aged 18-25.",
    benefits: "Mentorship and up to $20,000 in funding.",
    startDate: "2024-06-01",
    endDate: "2024-12-31",
  },
  {
    schemeID: "SCHEME-013",
    title: "ADA Senior Citizen Support",
    description: "Assistance for senior citizens.",
    status: "Closed",
    eligibility: "Senior citizens aged 60 and above.",
    benefits: "Financial assistance and healthcare support.",
    startDate: "2023-07-01",
    endDate: "2024-06-30",
  },
  {
    schemeID: "SCHEME-014",
    title: "ADA Disaster Relief Fund",
    description: "Support for disaster relief efforts.",
    status: "Open",
    eligibility: "Organizations involved in disaster relief.",
    benefits: "Funding and resources for disaster relief.",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
  },
];

module.exports = { schemes: schemes };
